### ISSUE TITLE
[ui]: make the y-axis start from 300 for "Lowest CRS Score"

### ISSUE THREAD

**Issue by ColossusChang** [Crayon-ShinChan/runiu#20]
Can you please make the y-axis start from 300 for "Lowest CRS Score"? This way the difference between the data points can be shown more clearly. Currently the space between 0 and 300 is just wasted away.

**Comment by Crayon-ShinChan** [comment]
Hi, thanks for the advice! This idea will definitely help the line chart accurately depict changes. However, sometimes the scores may fall below 300, as seen in the "Canadian Experience Class" over the past 5 years. Therefore, I believe that making the y-axis range dynamic to display all data points, instead of always setting it to 0 or 300, is a more robust approach. The dynamic y-axis range will not wasted too much space.
